### ISSUE TITLE
Do not collect c:/k/config in AKS Windows nodes

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-diskinspect-service#187]
c:/k/config contains credentials and it may not be helpful for troubleshooting. I do not have the background why we need to collect this file. @axelgMS, could you explain a bit more? Thanks.
https://github.com/Azure/azure-diskinspect-service/commit/fa3b6b626c2c7f1798d7e9cd595fbcde097f6e6b#diff-5479476b67bee0ed06b0852d806f953c23d87c96d34c7a38a1443dc53c854998

**Comment by axelgMS** [comment]
@AbelHu  this is coming from that PR
_adding kubelet config file to AKS manifest #[149](https://github.com/Azure/azure-diskinspect-service/pull/149)_

Background = CRI 190534195 where we found some weird characters can cause issues with CLI:
_Issue with special characters in SP credentials in latest version of Az CLI #[13625](https://github.com/Azure/azure-cli/issues/13625)_

Having the c:\k\config file helped us to narrow down and confirm the cause. Otherwise we might have spent much more time investigating.

**Comment by AbelHu** [comment]
@axelgMS did you need this config to logon to AKS nodes for investigation? I think that we can use SAW to get the kubeconfig and then access the AKS nodes so we do not need to collect kubeconfig with disk inspector.

**Comment by axelgMS** [comment]
@AbelHu No, we are not allowed to logon to AKS nodes. 

How do you get the kubelet config file from SAW? Do you mean you're getting it with Jarvis Actions? which one?
or with HcpDebug (I don't think we have permissions to run it).

**Comment by AbelHu** [comment]
@axelgMS AKS PG can use the tool in SAW to get kubeconfig to access the cluster after cx sends a request with an ICM for the help. kubeconfig is Highly Sensitive data and I think that we should not collect it with disk inspector.

**Comment by axelgMS** [comment]
@AbelHu sure, fine!
